[package]
name = "connect4-moderator-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.50", features = ["full"] }
tokio-tungstenite = "0.28"
futures-util = "0.3"
tracing = "0.1"
tracing-subscriber = "0.3"
anyhow = "1.0"
rand = "0.10"
async-trait = "0.1"
local-ip-address = "0.6"
